### ISSUE TITLE
matplotlib version mismatch maybe?

### ISSUE THREAD

**Issue by minhaj6** [CommonRoad/commonroad-scenario-designer#19]
Hi, 
WSL2 ubuntu on windows 10. Python 3.9. Matplotlib 3.9.1
installed using pip. 
I am wondering if this is a matplotlib version mismatch issue...

Error ->
```
camlab@DESKTOP-3LSSKO5:~$ crdesigner gui

Traceback (most recent call last):
  File "/home/camlab/.pyenv/versions/3.9.19/bin/crdesigner", line 5, in <module>
    from crdesigner.ui.command_line import cli
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/crdesigner/ui/command_line.py", line 12, in <module>
    from crdesigner.common.file_reader import CRDesignerFileReader
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/crdesigner/common/file_reader.py", line 11, in <module>
    from crdesigner.verification_repairing.map_verification_repairing import (
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/crdesigner/verification_repairing/map_verification_repairing.py", line 15, in <module>
    from crdesigner.verification_repairing.drawing.invalid_states.invalid_states_drawer import (
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/crdesigner/verification_repairing/drawing/invalid_states/invalid_states_drawer.py", line 15, in <module>
    from commonroad.visualization.mp_renderer import MPRenderer
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/commonroad/visualization/mp_renderer.py", line 68, in <module>
    from commonroad.visualization.traffic_sign import draw_traffic_light_signs
  File "/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/commonroad/visualization/traffic_sign.py", line 8, in <module>
    from matplotlib.axes import Axes, mtext
ImportError: cannot import name 'mtext' from 'matplotlib.axes' (/home/camlab/.pyenv/versions/3.9.19/lib/python3.9/site-packages/matplotlib/axes/__init__.py)
```

**Comment by smaierhofer** [comment]
Hi, yes, this is a matplotlib issue within commonroad-io.
We will fix this in the next release.

**Comment by minhaj6** [comment]
thank you

**Comment by minhaj6** [comment]
downgrading matplotlib to 3.8.3 fixed it.
