### ISSUE TITLE
Opendrive Conversion of map1.xodr from CARLA

### ISSUE THREAD

**Issue by ramdort** [CommonRoad/commonroad-scenario-designer#22]
I want to convert the Carla sample maps from opendrive to lanelets. By running this command ` crdesigner --input-file Town01.xodr --output-file Town01.osm odrlanelet2` i get this error. 
CRSError: Invalid projection: +lat_0=4.9000000000000000e+1 +lon_0=8.0000000000000000e+0 +type=crs: (Internal Proj Error: proj_create: unrecognized format / unknown 
name)
The map file can be found [here](https://github.com/carla-simulator/opendrive-test-files/blob/master/OpenDrive/Town01.xodr)
Could elaborate on that how to deal with ?
I have used other maps , I get always some warnings also related to projections from lanelet `Default origin should not be used when writing into a format that uses georeferenced lat/lon coordinates. Will continue to write the map, but the data will be dislocated and deformed`

**Comment by smaierhofer** [comment]
If you use the Python script, setting 
`open_drive_config.proj_string_odr = None`
should solve the problem. 

It is currently not possible to do this from the command line.

**Comment by ramdort** [comment]
I am trying to do it in a script 
``` 
from crdesigner.common.config import opendrive_config 
config = opendrive_config
config.proj_string_odr = None;
```

note there are difference between your and what is available to me in the script however when I run it I got an error 
![image](https://github.com/user-attachments/assets/c96b49e6-f558-4cdb-9480-d8b5ed86c551)

Thanks again in advance

**Comment by smaierhofer** [comment]
Are you using the function `opendrive_to_commonroad` in your script?
If not, please use this function.
Also provide as `odr_conf` argument the `config` object.

config = open_drive_config
config.proj_string_odr = None

scenario = opendrive_to_commonroad(input_path,  odr_conf=config)

**Comment by ramdort** [comment]
I do, see the figure
![image](https://github.com/user-attachments/assets/6f53c348-dd56-466e-a66d-9785dc909850)

**Comment by smaierhofer** [comment]
Which version of the scenario-designer have you installed?

**Comment by ramdort** [comment]
See pictures, I have reported a bug  earlier and have been recommend to get the debugged version of commonroad-scenario-designer from develop branch
![image](https://github.com/user-attachments/assets/c226c6b4-aaed-4c4d-a6e4-c697ade9411d)
![image](https://github.com/user-attachments/assets/2792c142-858c-47a0-a828-b6238ad7b031)

**Comment by ramdort** [comment]
I have edited the opendrive map and change the coordinates to other values as the following 2 lines 
```
<geoReference><![CDATA[+proj=tmerc +lat_0=5.1000000000000000e+1 +lon_0=1.0000000000000000e+1 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs]]></geoReference>
<geoReference><![CDATA[+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs]]></geoReference>
```

**Comment by smaierhofer** [comment]
I also just tried the develop branch again and for me the following code snippet works. 
Maybe the Python environment is corrupted and somehow and older version of the scenario-designer is used. 

```
import os
from pathlib import Path

from commonroad.planning.planning_problem import PlanningProblemSet
from commonroad.scenario.scenario import Tag

from crdesigner.common.config.opendrive_config import open_drive_config
from crdesigner.common.file_writer import CRDesignerFileWriter, OverwriteExistingFile
from crdesigner.map_conversion.map_conversion_interface import opendrive_to_commonroad

input_path = Path("/path/to/file/Town01.xodr")
output_path = Path("/path/to/file/Town01.xml")

config = open_drive_config
config.proj_string_odr = None

# load OpenDRIVE file, parse it, and convert it to a CommonRoad scenario
scenario = opendrive_to_commonroad(input_path, odr_conf=config)

# store converted file as CommonRoad scenario
writer = CRDesignerFileWriter(
    scenario=scenario,
    planning_problem_set=PlanningProblemSet(),
    author="Sebastian Maierhofer",
    affiliation="Technical University of Munich",
    source="CommonRoad Scenario Designer",
    tags={Tag.URBAN},
)

writer.write_to_file(str(output_path), OverwriteExistingFile.ALWAYS)

```

Updating, the geo-reference might lead to wrong results. 
From my experience, removing it completely is the better option (corresponds to setting the config.proj_string_odr = None in our code).

**Comment by ramdort** [comment]
It works fine but another problem appear the file is no longer readable by JOSM. 
`josm Town02.osm 
Using /usr/lib/jvm/java-21-openjdk-amd64/bin/java to execute josm.
2024-11-13 12:21:43.004 INFO: Log level is at INFO (INFO, 800)
2024-11-13 12:21:43.452 INFO: Detected usable IPv6 network, preferring IPv6 over IPv4.
2024-11-13 12:21:44.949 INFO: Obtained 168 Tag2Link rules from resource://META-INF/resources/webjars/tag2link/2024.10.21/index.json
2024-11-13 12:21:46.121 SEVERE: Failed to locate image 'presets/vehicle/firebrigade.svg'
2024-11-13 12:21:46.122 WARNING:  Emergency lane: Could not get presets icon presets/vehicle/firebrigade.svg
2024-11-13 12:21:46.126 SEVERE: Failed to locate image 'road_border.png'
2024-11-13 12:21:46.127 WARNING:  Road border: Could not get presets icon road_border.png
2024-11-13 12:21:46.127 SEVERE: Failed to locate image '101.png'
2024-11-13 12:21:46.127 WARNING:  Generic traffic sign: Could not get presets icon 101.png
2024-11-13 12:21:46.128 SEVERE: Failed to locate image 'pf-g.png'
2024-11-13 12:21:46.128 WARNING:  Arrow: Could not get presets icon pf-g.png
2024-11-13 12:21:46.258 INFO: Could not load tool definition splitway
2024-11-13 12:21:46.263 WARNING: Cannot lock cache directory. Will not use disk cache
2024-11-13 12:21:46.384 INFO: Changeset updater active (checks every 60 minutes if open changesets have been closed)
2024-11-13 12:21:46.434 INFO: Open file: /path/to/Town02.osm (2376461 bytes)
2024-11-13 12:21:46.437 INFO: Undefined element 'commonRoad' found in input stream. Skipping.
2024-11-13 12:21:46.921 INFO: Open file: /home/ /path/to/Town02.osm (2376461 bytes) completed in 488 ms`

**Comment by smaierhofer** [comment]
I just converted Town02 to Lanelet2 and for me loading the map in JOSM works.

**Comment by ramdort** [comment]
I want to add a point. I have converted the maps using the following command 
`crdesigner --input-file Town01.xodr --output-file Town01new.osm odrlanelet2` 
when I want to use some lanelet2 functionalities regrading distances I got a wrong high value. specifically `findNearest` function. In lanelet the points are projected to x,y before calling findNearest and I think that some wrong conversion from `crdesigner` please have on this [issue](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/377#issuecomment-2551827132) 
thanks

**Comment by stefanobortoli** [comment]
I am having similar issues with Town05

`(crdesigner) xxxx@xxxxx:~/dev/commonroad/crdesigner$ crdesigner --input-file Town05.xodr --output-file town05-cr.xml odrcr
Traceback (most recent call last):

  File "/home/XXXX/miniconda3/envs/crdesigner/bin/crdesigner", line 8, in <module>   sys.exit(cli())

  File "/home/xxx/miniconda3/envs/crdesigner/lib/python3.9/site-packages/crdesigner/ui/command_line.py", line 135, in odrcr
    scenario = opendrive_to_commonroad(ctx.obj["input_file"])

  File "/home/xxxx/miniconda3/envs/crdesigner/lib/python3.9/site-packages/crdesigner/map_conversion/map_conversion_interface.py", line 109, in opendrive_to_commonroad
    return road_network.export_commonroad_scenario(general_conf, odr_conf)

  File "/home/xxxx/miniconda3/envs/crdesigner/lib/python3.9/site-packages/crdesigner/map_conversion/opendrive/odr2cr/opendrive_conversion/network.py", line 654, in export_commonroad_scenario
    crs_from = CRS(self._geo_ref)

  File "/home/xxx/miniconda3/envs/crdesigner/lib/python3.9/site-packages/pyproj/crs/crs.py", line 348, in __init__
    self._local.crs = _CRS(self.srs)

  File "pyproj/_crs.pyx", line 2378, in pyproj._crs._CRS.__init__

pyproj.exceptions.CRSError: Invalid projection: +lat_0=4.9000000000000000e+1 +lon_0=8.0000000000000000e+0 +type=crs: (Internal Proj Error: proj_create: unrecognized format / unknown name)

`

**Comment by stefanobortoli** [comment]
just as an update, I tried the same toolchain with the master, installing all and starting scripts and gui from code. The result is the same.

pyproj.exceptions.CRSError: Invalid projection: +lat_0=4.9000000000000000e+1 +lon_0=8.0000000000000000e+0 +type=crs: (Internal Proj Error: proj_create: unrecognized format / unknown name)
